package io.electrum.airtime.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.electrum.airtime.api.model.Product;
import io.electrum.airtime.api.model.Receiver;
import io.electrum.airtime.api.model.Sender;
import io.electrum.airtime.api.model.SlipData;
import io.electrum.airtime.api.model.Voucher;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;



/**
 * Information about the voucher provisioned.
 **/

@ApiModel(description = "Information about the voucher provisioned.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-07-26T12:50:43.313Z")
public class VoucherResponse   {
  
  private String voucherId = null;
  private Product responseProduct = null;
  private Voucher voucher = null;
  private String time = null;
  private Sender sender = null;
  private Receiver receiver = null;
  private SlipData slipData = null;

  /**
   * A unique identifier generated by the client representing a specific voucher request.
   **/
  public VoucherResponse voucherId(String voucherId) {
    this.voucherId = voucherId;
    return this;
  }

  
  @ApiModelProperty(required = true, value = "A unique identifier generated by the client representing a specific voucher request.")
  @JsonProperty("voucherId")
  public String getVoucherId() {
    return voucherId;
  }
  public void setVoucherId(String voucherId) {
    this.voucherId = voucherId;
  }

  /**
   * The product for which the voucher was provisioned. This is assumed to be the product requested if this is absent.
   **/
  public VoucherResponse responseProduct(Product responseProduct) {
    this.responseProduct = responseProduct;
    return this;
  }

  
  @ApiModelProperty(value = "The product for which the voucher was provisioned. This is assumed to be the product requested if this is absent.")
  @JsonProperty("responseProduct")
  public Product getResponseProduct() {
    return responseProduct;
  }
  public void setResponseProduct(Product responseProduct) {
    this.responseProduct = responseProduct;
  }

  /**
   * The voucher provisioned if the vendor processed the request successfully.
   **/
  public VoucherResponse voucher(Voucher voucher) {
    this.voucher = voucher;
    return this;
  }

  
  @ApiModelProperty(value = "The voucher provisioned if the vendor processed the request successfully.")
  @JsonProperty("voucher")
  public Voucher getVoucher() {
    return voucher;
  }
  public void setVoucher(Voucher voucher) {
    this.voucher = voucher;
  }

  /**
   * The date and time of the request as recorded by the sender. The format shall be as defined for date-time in [RFC 3339 section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). It is recommended that the optional time-secfrac be included up to millisecond precision.
   **/
  public VoucherResponse time(String time) {
    this.time = time;
    return this;
  }

  
  @ApiModelProperty(required = true, value = "The date and time of the request as recorded by the sender. The format shall be as defined for date-time in [RFC 3339 section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). It is recommended that the optional time-secfrac be included up to millisecond precision.")
  @JsonProperty("time")
  public String getTime() {
    return time;
  }
  public void setTime(String time) {
    this.time = time;
  }

  /**
   **/
  public VoucherResponse sender(Sender sender) {
    this.sender = sender;
    return this;
  }

  
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("sender")
  public Sender getSender() {
    return sender;
  }
  public void setSender(Sender sender) {
    this.sender = sender;
  }

  /**
   **/
  public VoucherResponse receiver(Receiver receiver) {
    this.receiver = receiver;
    return this;
  }

  
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("receiver")
  public Receiver getReceiver() {
    return receiver;
  }
  public void setReceiver(Receiver receiver) {
    this.receiver = receiver;
  }

  /**
   **/
  public VoucherResponse slipData(SlipData slipData) {
    this.slipData = slipData;
    return this;
  }

  
  @ApiModelProperty(value = "")
  @JsonProperty("slipData")
  public SlipData getSlipData() {
    return slipData;
  }
  public void setSlipData(SlipData slipData) {
    this.slipData = slipData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoucherResponse voucherResponse = (VoucherResponse) o;
    return Objects.equals(voucherId, voucherResponse.voucherId) &&
        Objects.equals(responseProduct, voucherResponse.responseProduct) &&
        Objects.equals(voucher, voucherResponse.voucher) &&
        Objects.equals(time, voucherResponse.time) &&
        Objects.equals(sender, voucherResponse.sender) &&
        Objects.equals(receiver, voucherResponse.receiver) &&
        Objects.equals(slipData, voucherResponse.slipData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voucherId, responseProduct, voucher, time, sender, receiver, slipData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoucherResponse {\n");
    
    sb.append("    voucherId: ").append(toIndentedString(voucherId)).append("\n");
    sb.append("    responseProduct: ").append(toIndentedString(responseProduct)).append("\n");
    sb.append("    voucher: ").append(toIndentedString(voucher)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    slipData: ").append(toIndentedString(slipData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

